### PR TITLE
nuFAR compatibility

### PR DESCRIPTION
**Pull request by ZiwKerman**
Every 60th FixedUpdate MuMechToggle needs to send a message to its
parent part and all children to update the shape, which will trigger
nuFARs voxel model rebuild

### CODE REVIEW

**Comment by erendrake** [comment]
@ZiwKerman a few thoughts
1. Was 60 just an arbitrary span? with users being able to change their fixed update span it seem like you could get a different behavior depending on user settings.
2. Could we avoid sending the message if the toggle hasnt moved?

**Comment by ZiwKerman** [comment]
1. I messaged with ferram on forums and we agreed that this is frequent enough to be relevant and on the other hand will not bring too much strain on the user's system, because voxel model rebuilding is CPU intensive process.
2. If you look close enough you'll see that I've put a threshold that prevents sending message if lastPosition is less than 0.005 away from current position

**Comment by erendrake** [comment]
1. good enough for ferram, good enough for me :)
2. so right you are. i just missed it :) 

looks-good-to-me-ship-it

**Comment by ZodiusInfuser** [comment]
When you say you only trigger an update if the new position is different from the current position, I assume you also only update the current position then too?

**Pull request merged**
