### PR TITLE
Fixes to TweakScale Interaction and Symmetry

### PR DESCRIPTION
**Pull request by ZiwKerman**
#49

### CODE REVIEW

**Comment by ZiwKerman** [comment]
Tested it on 3 systems, should be alright for develop branch.

**Comment by erendrake** [comment]
In mechanism base. You have multiple lines that all fetch and cast the module. That should be done once.

**Comment by erendrake** [comment]
At the start of each iteration

**Comment by ZiwKerman** [comment]
Copy/Pasted the code without much thought. Will fix that

**Pull request merged**
